/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MapRouteImport } from './routes/map'
import { Route as IftaRouteImport } from './routes/ifta'
import { Route as HosRouteImport } from './routes/hos'
import { Route as DvirRouteImport } from './routes/dvir'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DIndexRouteImport } from './routes/d/index'
import { Route as DTripRouteImport } from './routes/d/trip'
import { Route as DMessagesRouteImport } from './routes/d/messages'
import { Route as DInspectionRouteImport } from './routes/d/inspection'
import { Route as DFuelRouteImport } from './routes/d/fuel'
import { Route as DDvirRouteImport } from './routes/d/dvir'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IftaRoute = IftaRouteImport.update({
  id: '/ifta',
  path: '/ifta',
  getParentRoute: () => rootRouteImport,
} as any)
const HosRoute = HosRouteImport.update({
  id: '/hos',
  path: '/hos',
  getParentRoute: () => rootRouteImport,
} as any)
const DvirRoute = DvirRouteImport.update({
  id: '/dvir',
  path: '/dvir',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DIndexRoute = DIndexRouteImport.update({
  id: '/d/',
  path: '/d/',
  getParentRoute: () => rootRouteImport,
} as any)
const DTripRoute = DTripRouteImport.update({
  id: '/d/trip',
  path: '/d/trip',
  getParentRoute: () => rootRouteImport,
} as any)
const DMessagesRoute = DMessagesRouteImport.update({
  id: '/d/messages',
  path: '/d/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DInspectionRoute = DInspectionRouteImport.update({
  id: '/d/inspection',
  path: '/d/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const DFuelRoute = DFuelRouteImport.update({
  id: '/d/fuel',
  path: '/d/fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const DDvirRoute = DDvirRouteImport.update({
  id: '/d/dvir',
  path: '/d/dvir',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/drivers': typeof DriversRoute
  '/dvir': typeof DvirRoute
  '/hos': typeof HosRoute
  '/ifta': typeof IftaRoute
  '/map': typeof MapRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/vehicles': typeof VehiclesRoute
  '/d/dvir': typeof DDvirRoute
  '/d/fuel': typeof DFuelRoute
  '/d/inspection': typeof DInspectionRoute
  '/d/messages': typeof DMessagesRoute
  '/d/trip': typeof DTripRoute
  '/d/': typeof DIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/drivers': typeof DriversRoute
  '/dvir': typeof DvirRoute
  '/hos': typeof HosRoute
  '/ifta': typeof IftaRoute
  '/map': typeof MapRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/vehicles': typeof VehiclesRoute
  '/d/dvir': typeof DDvirRoute
  '/d/fuel': typeof DFuelRoute
  '/d/inspection': typeof DInspectionRoute
  '/d/messages': typeof DMessagesRoute
  '/d/trip': typeof DTripRoute
  '/d': typeof DIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/drivers': typeof DriversRoute
  '/dvir': typeof DvirRoute
  '/hos': typeof HosRoute
  '/ifta': typeof IftaRoute
  '/map': typeof MapRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/vehicles': typeof VehiclesRoute
  '/d/dvir': typeof DDvirRoute
  '/d/fuel': typeof DFuelRoute
  '/d/inspection': typeof DInspectionRoute
  '/d/messages': typeof DMessagesRoute
  '/d/trip': typeof DTripRoute
  '/d/': typeof DIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/dashboard'
    | '/devices'
    | '/drivers'
    | '/dvir'
    | '/hos'
    | '/ifta'
    | '/map'
    | '/messages'
    | '/onboarding'
    | '/settings'
    | '/vehicles'
    | '/d/dvir'
    | '/d/fuel'
    | '/d/inspection'
    | '/d/messages'
    | '/d/trip'
    | '/d/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/dashboard'
    | '/devices'
    | '/drivers'
    | '/dvir'
    | '/hos'
    | '/ifta'
    | '/map'
    | '/messages'
    | '/onboarding'
    | '/settings'
    | '/vehicles'
    | '/d/dvir'
    | '/d/fuel'
    | '/d/inspection'
    | '/d/messages'
    | '/d/trip'
    | '/d'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/dashboard'
    | '/devices'
    | '/drivers'
    | '/dvir'
    | '/hos'
    | '/ifta'
    | '/map'
    | '/messages'
    | '/onboarding'
    | '/settings'
    | '/vehicles'
    | '/d/dvir'
    | '/d/fuel'
    | '/d/inspection'
    | '/d/messages'
    | '/d/trip'
    | '/d/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DevicesRoute: typeof DevicesRoute
  DriversRoute: typeof DriversRoute
  DvirRoute: typeof DvirRoute
  HosRoute: typeof HosRoute
  IftaRoute: typeof IftaRoute
  MapRoute: typeof MapRoute
  MessagesRoute: typeof MessagesRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  VehiclesRoute: typeof VehiclesRoute
  DDvirRoute: typeof DDvirRoute
  DFuelRoute: typeof DFuelRoute
  DInspectionRoute: typeof DInspectionRoute
  DMessagesRoute: typeof DMessagesRoute
  DTripRoute: typeof DTripRoute
  DIndexRoute: typeof DIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ifta': {
      id: '/ifta'
      path: '/ifta'
      fullPath: '/ifta'
      preLoaderRoute: typeof IftaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hos': {
      id: '/hos'
      path: '/hos'
      fullPath: '/hos'
      preLoaderRoute: typeof HosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dvir': {
      id: '/dvir'
      path: '/dvir'
      fullPath: '/dvir'
      preLoaderRoute: typeof DvirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/': {
      id: '/d/'
      path: '/d'
      fullPath: '/d/'
      preLoaderRoute: typeof DIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/trip': {
      id: '/d/trip'
      path: '/d/trip'
      fullPath: '/d/trip'
      preLoaderRoute: typeof DTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/messages': {
      id: '/d/messages'
      path: '/d/messages'
      fullPath: '/d/messages'
      preLoaderRoute: typeof DMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/inspection': {
      id: '/d/inspection'
      path: '/d/inspection'
      fullPath: '/d/inspection'
      preLoaderRoute: typeof DInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/fuel': {
      id: '/d/fuel'
      path: '/d/fuel'
      fullPath: '/d/fuel'
      preLoaderRoute: typeof DFuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/dvir': {
      id: '/d/dvir'
      path: '/d/dvir'
      fullPath: '/d/dvir'
      preLoaderRoute: typeof DDvirRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DevicesRoute: DevicesRoute,
  DriversRoute: DriversRoute,
  DvirRoute: DvirRoute,
  HosRoute: HosRoute,
  IftaRoute: IftaRoute,
  MapRoute: MapRoute,
  MessagesRoute: MessagesRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  VehiclesRoute: VehiclesRoute,
  DDvirRoute: DDvirRoute,
  DFuelRoute: DFuelRoute,
  DInspectionRoute: DInspectionRoute,
  DMessagesRoute: DMessagesRoute,
  DTripRoute: DTripRoute,
  DIndexRoute: DIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
